In [1]:
import numpy as np

In [2]:
# Initialize input
X = np.array([[1, 0, 1, 0],
              [1, 0, 1, 1],
              [0, 1, 0, 1]])

In [3]:
# Randomly initialize Weights
W = np.array([[.42, .88 , .55],
             [.1, .73, .68],
             [.6, .18, .47],
             [.92, .11, .52]])

In [52]:
W = np.random.random(size=(4,3))
W

array([[0.48349947, 0.43856219, 0.09061309],
       [0.56103964, 0.03150729, 0.02310984],
       [0.24951628, 0.80523213, 0.55870699],
       [0.81335436, 0.09536998, 0.95689467]])

In [4]:
# Randomly initialize biases
b = np.array([.46, .72, .08])

In [53]:
b = np.random.random(size=(3, 1))
b

array([[0.69092939],
       [0.54861474],
       [0.04688339]])

In [54]:
# Calculate output of hidden layer 1
hidden = np.dot(X, W) + b
hidden

array([[1.42394514, 1.93472371, 1.34024946],
       [2.09498485, 1.88777905, 2.15482948],
       [1.42127739, 0.17376066, 1.0268879 ]])

In [55]:
# Applying Sigmoid
hidden_activation = 1/(1 + np.exp(-hidden))
hidden_activation

array([[0.80595615, 0.87377134, 0.79253096],
       [0.89041478, 0.86850209, 0.89611921],
       [0.80553859, 0.5433312 , 0.7363121 ]])

In [11]:
#Used for checking first time
W_out = np.array([0.3, 0.25, 0.23])
b_out = 0.69

In [56]:
# Random initialisation
W_out = np.random.random(size=(3,1))
b_out = np.random.random(size=1)

In [57]:
W_out, b_out

(array([[0.78926818],
        [0.15470272],
        [0.8590978 ]]), array([0.73721703]))

In [58]:
output = np.dot(hidden_activation, W_out) + b_out
output

array([[2.18936898],
       [2.34420676],
       [2.08962193]])

In [13]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [59]:
output_activation = sigmoid(output)
output_activation

array([[0.89929077],
       [0.91247265],
       [0.88989039]])

In [60]:
# Store output in y
Y = np.array([1, 1, 0])

In [61]:
def derivative_sigmoid(x):
    return x * (1 -x)

In [65]:
Y.shape, output_activation.shape

((3,), (3, 1))

In [66]:
E = Y.reshape(3,1) - output_activation
E

array([[ 0.10070923],
       [ 0.08752735],
       [-0.88989039]])

In [24]:
# Calculate derivate at output layer
slope_op = derivative_sigmoid(output_activation)
print('Slope at Output Layer')
print(slope_op)

slope_hidden = derivative_sigmoid(hidden_activation)
print("Slope at Hidden Layer")
print(slope_hidden)

Slope at Output Layer
[0.16629159 0.16115766 0.16628507]
Slope at Hidden Layer
[[0.15104409 0.12347974 0.18736988]
 [0.076255   0.11401936 0.13791222]
 [0.15104409 0.14349349 0.17022212]]


In [67]:
# Setting Learning rate

lr = 0.1

In [69]:
E.shape, slope_op.shape

((3, 1), (3,))

In [70]:
#Compute Delta at Output Layer

delta_op = E.reshape(3) * slope_op
delta_op

array([ 0.0167471 ,  0.0141057 , -0.14797549])

In [71]:
# Checking shapes

delta_op.shape, W_out.shape

((3,), (3, 1))

In [72]:
delta_op = delta_op.reshape(delta_op.shape[0], 1)
W_out = W_out.reshape(W_out.shape[0], 1)

In [73]:
#Compute Error at Hidden Layer

error_hidden = np.dot(delta_op, W_out.T)
error_hidden

array([[ 0.01321795,  0.00259082,  0.01438739],
       [ 0.01113318,  0.00218219,  0.01211818],
       [-0.11679234, -0.02289221, -0.12712541]])

In [74]:
#Compute Delta at Hidden Layer
# Error at Hidden Layer * Slope at Hidden Layer

delta_hidden = error_hidden * slope_hidden
delta_hidden

array([[ 0.00199649,  0.00031991,  0.00269576],
       [ 0.00084896,  0.00024881,  0.00167124],
       [-0.01764079, -0.00328488, -0.02163956]])

In [75]:
#Update Weights
#wout = wout + matrix_dot_product(hiddenlayer_activations.Transpose, d_output)*learning_rate
#wh =  wh+ matrix_dot_product(X.Transpose,d_hiddenlayer)*learning_rate

W_out = W_out + np.dot(hidden_activation.T, delta_op) * lr
W = W + + np.dot(X.T, delta_hidden) * lr

In [76]:
W_out

array([[0.77995392],
       [0.14935115],
       [0.85079348]])

In [77]:
W

array([[0.48378402, 0.43861907, 0.09104979],
       [0.55927556, 0.0311788 , 0.02094588],
       [0.24980083, 0.805289  , 0.55914369],
       [0.81167517, 0.09506638, 0.95489784]])

In [81]:
b_out = np.array([0.73721703])
b_out.shape

(1,)

In [82]:
#Update Biases
#bh = bh + sum(d_hiddenlayer, axis=0) * learning_rate
#bout = bout + sum(d_output, axis=0)*learning_rate
b = b.reshape(b.shape[0]) + np.sum(delta_hidden, axis=0) * lr
b_out = b_out.reshape(b_out.shape[0]) + np.sum(delta_op, axis=0) * lr

In [83]:
b, b_out

(array([0.68944986, 0.54834312, 0.04515614]), array([0.72550476]))